#!/bin/sh
$ cat Allclean
cd ${0%/*} || exit 1    # Run from this directory

# Put stl files to constant/triSurface

(surfaceFeatureExtract && blockMesh && snappyHexMesh -overwrite && checkMesh) | tee meshing.log